actions/python-setup-poetry/README.md, actions/python-setup-poetry/action.yaml
=> Allow passing custom Poetry working directory

.github/actionlint-matcher.json, .github/workflows/helm-release.yaml, .github/workflows/lint.yaml
Run actionlint and report problems as line comments.
example
=> Set up pipeline for linting actions & workflows

actions/python-poetry-bump-version/README.md, actions/python-poetry-bump-version/action.yaml, actions/python-poetry-release/README.md, actions/python-poetry-release/action.yaml, actions/python-setup-poetry/README.md, actions/python-setup-poetry/action.yaml
Patch for PyPI API change https://github.com/python-poetry/poetry/releases/tag/1.1.14
=> Update poetry to 1.1.14

.github/workflows/python-poetry-release.yaml, actions/python-poetry-release/action.yaml
Fixes https://github.com/bakdata/streams-explorer/runs/8223131732?check_suite_focus=true
=> Fix Poetry release with custom working directory

actions/bump-version/README.md, actions/python-poetry-bump-version/README.md, actions/python-poetry-bump-version/action.yaml, actions/python-poetry-release/README.md, actions/python-poetry-release/action.yaml, actions/python-setup-poetry/README.md, actions/python-setup-poetry/action.yaml
- Update Poetry to 1.2.1
- Update setup-python action
=> Update Poetry to 1.2.1

actions/bump-version/README.md, actions/bump-version/action.yaml
=> Support custom working directory for bumpversion action

.github/workflows/test-python-setup-poetry.yaml, .tests/poetry/poetry.lock, .tests/poetry/pyproject.toml, actions/python-poetry-bump-version/README.md, actions/python-poetry-bump-version/action.yaml, actions/python-poetry-release/README.md, actions/python-poetry-release/action.yaml, actions/python-setup-poetry/README.md, actions/python-setup-poetry/action.yaml
Fixes #33
added a test workflow to verify that the correct versions of Python and Poetry are set up. It automatically runs when changes are made to the python-setup-poetry action or to the test workflow itself.
=> Fix Poetry setup on Windows

.github/workflows/README.md, .github/workflows/kustomize-gke-deploy.yaml, .github/workflows/kustomize-gke-destroy.yaml, actions/kustomize-gke-deploy/README.md, actions/kustomize-gke-deploy/action.yaml, actions/kustomize-gke-destroy/README.md, actions/kustomize-gke-destroy/action.yaml
=> Create CI template for Kustomize deploy/destroy

actions/kpops-runner/README.md, actions/kpops-runner/action.yaml
=> Add kpops version param to kpops-runner action

.github/workflows/kustomize-gke-deploy.yaml, .github/workflows/kustomize-gke-destroy.yaml, actions/kustomize-gke-deploy/action.yaml
=> Fix Kustomize GKE deploy action not running without CRDs

.github/workflows/README.md, .github/workflows/helm-multi-release.yaml
Fixes #37 
Fixes #38
Reusable workflow for packaging and publishing Helm charts having multiple subcharts on GitHub pages
=> Add Helm Multi Release

.github/workflows/README.md, .github/workflows/python-poetry-release.yaml, actions/commit-and-push/README.md, actions/python-poetry-bump-version/README.md, actions/python-poetry-bump-version/action.yaml, actions/python-poetry-release/README.md, actions/python-poetry-release/action.yaml
Add checkout action in example with `persist-credentials: false`
=> Update documentation for Poetry release

.github/workflows/format.yaml, CONTRIBUTING.md, README.md, actions/bump-version/README.md, actions/java-gradle-build-jib/README.md, actions/java-gradle-build/README.md, actions/kpops-runner/README.md, actions/kustomize-gke-destroy/README.md, dprint.json
Ran `dprint` to format markdown tables
=> Format docs

.github/workflows/README.md, .github/workflows/docker-build-and-publish.yaml, .github/workflows/lint.yaml, actions/docker-build/README.md, actions/docker-build/action.yaml, actions/docker-publish/README.md, actions/docker-publish/action.yaml
=> Publish Docker image to any host

.github/workflows/README.md
=> Fix broken link in the readme

actions/commit-and-push/README.md, actions/commit-and-push/action.yaml
=>  Add flag to avoid fail upon nothing to commit in Commit and push action

.github/workflows/python-poetry-release.yaml, actions/python-poetry-bump-version/action.yaml
needed for https://github.com/bakdata/kpops/pull/200
=> Add Poetry bumpversion plugin

.github/workflows/README.md, .github/workflows/python-poetry-publish-snapshot.yaml
=> Create Poetry publish workflow for dev snapshots

actions/port-forward/README.md, actions/port-forward/action.yaml
=> Add timeout var and force fail when timeout is reached

.github/workflows/_release.yaml, actions/changelog-generate/action.yaml
- Remove reference to missing changelog config
- Abort if changelog config file doesn't exist
=> Remove reference to missing changelog config

actions/java-gradle-assess-code-quality/action.yaml, actions/java-gradle-publish-plugin/action.yml, actions/java-gradle-publish/action.yaml
Make sure playground repos never release a java project on accident
=> feat: block java release on playground repo

actions/python-setup-poetry/action.yaml
install poetry runs quite often (e.g. during kpops setup) and always takes 5-10sec. Therefore caching it probably makes sense
=> Feature: Cache poetry installation

.github/workflows/java-gradle-base.yaml, .github/workflows/java-gradle-docker.yaml, .github/workflows/java-gradle-library.yaml, .github/workflows/java-gradle-plugin.yaml, actions/java-gradle-assess-code-quality/action.yaml
https://docs.sonarsource.com/sonarqube-server/10.8/analyzing-source-code/scanners/scanner-environment/verifying-code-checkout-step/
=> Configure sonar fetch depth for better new code detection

actions/changelog-generate/action.yaml, docs/actions/changelog-generate/README.md
- **hotfix: remove everything git-cliff related (brutally)**
- **hotfix: also remove git-cliff binary (cold-blooded)**
amend to #272
=> hotfix 2: also remove git-cliff binary

.github/workflows/python-poetry-publish-pypi.yaml, actions/python-poetry-bump-version/action.yaml, actions/python-setup-poetry/action.yaml
I have no idea how this worked previously
=> fix: let Poetry assume custom Python version in setup action
